import { describe, it, expect } from 'vitest';
import { findCacheBusters, applyCacheFixes } from '../../../src/optimizer/cache-applier.js';

const CLEAN_CONTENT = `# My Project

## Commands

Run \`npm start\` to launch the server.
Use \`npm test\` for tests.

## Architecture

This is a stable architecture section.
No dynamic content here.
`;

const DIRTY_CONTENT = `# My Project

Last updated: 2026-04-11
Session date: 2026-04-11 18:00:00

## Commands

Run \`npm start\` to launch the server.

## Notes

Generated by claude-code on 2026-04-11
Version: 1.2.3
`;

describe('findCacheBusters', () => {
  it('returns empty array for clean content', () => {
    const fixes = findCacheBusters(CLEAN_CONTENT);
    expect(fixes).toHaveLength(0);
  });

  it('detects "Last updated" lines', () => {
    // Use content without a bare date so the Date pattern does not claim the line first
    const content = 'Last updated: recently';
    const fixes = findCacheBusters(content);
    expect(fixes.some((f) => f.label === '"Last updated" timestamp')).toBe(true);
  });

  it('detects date strings (YYYY-MM-DD)', () => {
    const fixes = findCacheBusters(DIRTY_CONTENT);
    const dateFix = fixes.find((f) => f.label === 'Date string');
    expect(dateFix).toBeTruthy();
  });

  it('detects time strings (HH:MM:SS)', () => {
    const content = 'Session started at 14:32:01';
    const fixes = findCacheBusters(content);
    expect(fixes.some((f) => f.label === 'Time string')).toBe(true);
  });

  it('detects "Generated by" lines', () => {
    // Use content without a date so the Date pattern does not claim the line first
    const content = 'Generated by claude-code';
    const fixes = findCacheBusters(content);
    expect(fixes.some((f) => f.label === 'Generator comment')).toBe(true);
  });

  it('detects version strings', () => {
    const fixes = findCacheBusters(DIRTY_CONTENT);
    expect(fixes.some((f) => f.label === 'Version string')).toBe(true);
  });

  it('only flags each line once even if multiple patterns match', () => {
    // "Last updated: 2026-04-11" could match both Date string AND Last updated
    const content = 'Last updated: 2026-04-11';
    const fixes = findCacheBusters(content);
    expect(fixes).toHaveLength(1);
  });

  it('returns correct line numbers (1-based)', () => {
    const content = 'line one\nline two\nLast updated: 2026-04-11\nline four';
    const fixes = findCacheBusters(content);
    expect(fixes[0].lineNumber).toBe(3);
  });

  it('preserves original line text', () => {
    const content = 'Last updated: 2026-04-11';
    const fixes = findCacheBusters(content);
    expect(fixes[0].originalLine).toBe('Last updated: 2026-04-11');
  });

  it('generates a comment-style fixed line', () => {
    const content = 'Last updated: 2026-04-11';
    const fixes = findCacheBusters(content);
    expect(fixes[0].fixedLine).toContain('<!--');
    expect(fixes[0].fixedLine).toContain('-->');
  });
});

describe('applyCacheFixes', () => {
  it('replaces flagged lines with comments', () => {
    const content = 'Last updated: 2026-04-11\nStable line';
    const fixes = findCacheBusters(content);
    const result = applyCacheFixes(content, fixes);
    expect(result).toContain('<!--');
    expect(result).toContain('Stable line');
  });

  it('does not modify lines that are not in fixes list', () => {
    const fixes = findCacheBusters(DIRTY_CONTENT);
    const result = applyCacheFixes(DIRTY_CONTENT, fixes);
    expect(result).toContain('## Commands');
    expect(result).toContain('npm start');
  });

  it('returns identical content when fixes list is empty', () => {
    const result = applyCacheFixes(CLEAN_CONTENT, []);
    expect(result).toBe(CLEAN_CONTENT);
  });
});
