import * as fs from 'fs';
import * as path from 'path';

export interface IgnorefileResult {
  filePath: string;
  content: string;
  existed: boolean;
  projectTypes: string[];
}

const ALWAYS_IGNORE = `# .claudeignore — generated by claudectx
# Prevents Claude Code from accidentally reading large binary/generated files.
# Syntax is identical to .gitignore.

# Version control internals
.git/

# Dependencies
node_modules/
vendor/
.venv/
venv/
env/
.env/

# Build output
dist/
build/
out/
.next/
.nuxt/
.output/
target/

# Bytecode & compiled files
*.pyc
*.pyo
__pycache__/
*.class
*.o
*.a
*.so
*.dylib

# Logs & databases
*.log
logs/
*.sqlite3
*.sqlite
*.db

# OS artefacts
.DS_Store
Thumbs.db
desktop.ini

# Environment & secrets (never let Claude read these)
.env
.env.local
.env.*.local
*.pem
*.key
*.cert
secrets.json

# Coverage & test caches
coverage/
.coverage
htmlcov/
.cache/
.pytest_cache/
.mypy_cache/
.ruff_cache/
.tox/

# IDE files
.idea/
.vscode/
*.swp
*.swo
*~

# Large media / binary assets
*.jpg
*.jpeg
*.png
*.gif
*.ico
*.mp4
*.mp3
*.pdf
*.zip
*.tar.gz
*.woff
*.woff2
*.ttf
*.eot
`;

const PYTHON_EXTRA = `
# Python / Django extras
migrations/
staticfiles/
media/
.eggs/
*.egg-info/
pip-wheel-metadata/
`;

const NODE_EXTRA = `
# Node.js lock files (large, rarely useful to Claude)
package-lock.json
yarn.lock
pnpm-lock.yaml
.yarn/
`;

const RUST_EXTRA = `
# Rust
Cargo.lock
`;

const GO_EXTRA = `
# Go
go.sum
`;

function detectProjectTypes(projectRoot: string): string[] {
  const types: string[] = [];
  if (fs.existsSync(path.join(projectRoot, 'package.json'))) types.push('node');
  if (
    fs.existsSync(path.join(projectRoot, 'manage.py')) ||
    fs.existsSync(path.join(projectRoot, 'requirements.txt')) ||
    fs.existsSync(path.join(projectRoot, 'pyproject.toml'))
  )
    types.push('python');
  if (fs.existsSync(path.join(projectRoot, 'Cargo.toml'))) types.push('rust');
  if (fs.existsSync(path.join(projectRoot, 'go.mod'))) types.push('go');
  return types;
}

export function generateIgnorefile(projectRoot: string): IgnorefileResult {
  const filePath = path.join(projectRoot, '.claudeignore');
  const existed = fs.existsSync(filePath);
  const projectTypes = detectProjectTypes(projectRoot);

  let content = ALWAYS_IGNORE;
  if (projectTypes.includes('python')) content += PYTHON_EXTRA;
  if (projectTypes.includes('node')) content += NODE_EXTRA;
  if (projectTypes.includes('rust')) content += RUST_EXTRA;
  if (projectTypes.includes('go')) content += GO_EXTRA;

  return { filePath, content, existed, projectTypes };
}

export function writeIgnorefile(result: IgnorefileResult): void {
  if (result.existed) {
    const existing = fs.readFileSync(result.filePath, 'utf-8');
    fs.writeFileSync(result.filePath, existing.trimEnd() + '\n\n' + result.content, 'utf-8');
  } else {
    fs.writeFileSync(result.filePath, result.content, 'utf-8');
  }
}
