/** Claude Code built-in token overhead (sent on every request, cannot be reduced) */
export const BUILTIN_OVERHEAD = {
  /** Claude Code's own system prompt */
  SYSTEM_PROMPT: 4200,
  /** Built-in tool schemas (Read, Edit, Bash, Glob, Grep, etc.) */
  TOOL_DEFINITIONS: 2100,
  /** Approximate tokens per registered MCP tool schema */
  MCP_PER_TOOL: 180,
} as const;

/** Waste detection thresholds */
export const WASTE_THRESHOLDS = {
  /** CLAUDE.md token count above this triggers OVERSIZED_CLAUDEMD */
  MAX_CLAUDEMD_TOKENS: 2000,
  /** MEMORY.md token count above this triggers OVERSIZED_MEMORY */
  MAX_MEMORY_TOKENS: 3000,
  /** Referenced file token count above this triggers LARGE_REFERENCE_FILE */
  MAX_REFERENCE_FILE_TOKENS: 5000,
  /** Number of @referenced files above this triggers TOO_MANY_REFERENCES */
  MAX_REFERENCE_COUNT: 5,
} as const;

/** Default session assumptions for cost estimates */
export const SESSION_DEFAULTS = {
  /** Assumed number of requests in a typical 2-hour session */
  REQUESTS_PER_SESSION: 60,
} as const;

/** Regex patterns that break prompt caching */
export const CACHE_BUSTERS = [
  { pattern: /\d{4}-\d{2}-\d{2}/g, label: 'Date string' },
  { pattern: /\d{2}:\d{2}:\d{2}/g, label: 'Time string' },
  { pattern: /process\.env\.\w+/g, label: 'Environment variable reference' },
  { pattern: /\$\{.*?\}/g, label: 'Template literal with variable' },
  { pattern: /Last updated:.*/gi, label: '"Last updated" timestamp' },
  { pattern: /Version:.*\d+\.\d+/gi, label: 'Version string' },
  { pattern: /Generated by.*/gi, label: 'Generator comment' },
] as const;
